# Generated by Django 4.2.6 on 2023-11-05 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
