# Generated by Django 4.2.6 on 2023-10-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_user_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='mail',
            field=models.CharField(default='abc@gmail.com', max_length=50),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
